name = "static-test"
type = "webpack"
workers_dev = true
account_id = "dc56444c4c955a1653106ccf997c1067"

[env.production]
name = "static-test-prod"

[site]
bucket = "./public"
entry-point = "workers-site"
