on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - name: Build app
      run: "echo 'noop - build not needed for this project'"
    - name: Publish app
      uses: signalnerve/wrangler-action@0.0.19
      with:
        CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
        CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
