on:
  push:
    branches:
      - master
  repository_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - uses: actions/checkout@master
    - name: Build app
      run: "echo 'noop - build not needed for this project'"
    - name: Publish app
      uses: signalnerve/wrangler-action@master
      with:
        apiKey: ${{ secrets.CLOUDFLARE_API_KEY }}
        email: ${{ secrets.CLOUDFLARE_EMAIL }}
        environment: "production"
    - name: Validate scraper (single)
      uses: signalnerve/scraper-action@0.0.6
      with:
        url: "https://static-test-prod.signalnerve.workers.dev/"
        selector: "h1"
        test: "ooo it's a site"
        debug: true
    - name: Validate scraper (multiple)
      uses: signalnerve/scraper-action@0.0.6
      with:
        file: "scraper_tests.json"
        debug: true
